### ISSUE TITLE
Organize code vertically by feature

### ISSUE THREAD

**Issue by vincanger** [wardbox/roke#32]
Generally, it would make the file structure cleaner and the app would be easier to understand and navigate if files were grouped based on feature and/or functionality.

First off, your `src/client/example` folder contains an `operations.ts` file, so it would make sense to move this folder (and all other feature folders) to the top of `src`, since they contain both client and server code.

As another example, your `components` folder currently looks like this:

```sh
└── components
    ├── landing            # All Landing Page related Page, component, and helper files 
    ├── ui
    └── some-other-files.tsx
```

I would do the same thing as with `example` and move `landing` a level up so that it is within `src`, and move the `ui` folder to `client`. If there are any components within the `ui` folder that are specific to certain features or functionality, you can move those to their respective feature folders, e.g. `some-feature/components`. There may be some overlap here and, for example, there may be reusable components that could potentially live in more than one folder. That's fine. Just choose the one that seems to make the most sense.

Also, you have many framer-motion related files strewn about. Because the template is so animation focused, I would suggest that these could all be consolidated into a folder called e.g. `motion` :

```sh
└── src
    └── motion
        ├── config
        ├── components  
        └── other-motion-files.tsx
```

I would also move `src/components/ui/motion.tsx` here and rename it to something more descriptive like `transitionsPresets.ts`. Same with `src/types/motion.ts`. Since there is only one type, just delete that file and add the type to the top of the file where it would make the most sense to live, like `transitionsPresets.ts` perhaps.

These are just a few examples I could find. I'm sure there is more that could benefit from reorganization. You will probably know best but let me know if you have any questions or need any help here. We can also have a quick call on discord to clarify anything if you need.

**Comment by wardbox** [comment]
@vincanger thanks for the guidance on these, it's looking way cleaner.

**Comment by vincanger** [comment]
Looks great! @wardbox
